<?php
	
	$tab = ( array(
		'id'           => 'strive_wookc_coupon_page',
		'title'        => esc_html__( 'Coupon options','woocommerce' ),
		'object_types' => array('options-page'),
		'option_key'   => 'strive_wookc_coupon_page_options',
		'parent_slug'  => 'strive_wookc_main_options',
	) );

	if ( version_compare( CMB2_VERSION, '2.4.0' ) ) {
		$tab['display_cb'] = 'yourprefix_options_display_with_tabs';
	}
	
		$coupon_options = new_cmb2_box($tab); 
	
	/*
		https://www.businessbloomer.com/woocommerce-slashed-cart-subtotal-coupon-cart/
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable', 'woocommerce' ),
		'desc' => esc_html__( 'total sales generated by each coupon code' ),
		'id'   => 'strive_Wookc_subtotal_if_discount',
		'type' => 'checkbox',
	) );


	/*
		https://www.businessbloomer.com/woocommerce-change-coupon-code-message-cart-checkout/
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable/Disable', 'woocommerce' ),
		'desc' => esc_html__( 'Editing Have a Coupon In Display ?' ),
		'id'   => 'strive_wookc_have_coupon_message',
		'type' => 'checkbox',
	) );
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable Checkbox ?', 'woocommerce' ),
		'desc' => esc_html__( 'Add Your Message?' ),
		'id'   => 'strive_wookc_coupon_message',
		'type' => 'text',
	) );



	/*
		https://www.businessbloomer.com/woocommerce-hide-coupon-code-cartcheckout-page/
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable/Disable','woocommerce'),
		'desc' => esc_html__( ' Hide Coupon Codes On The Cart Page ?' ),
		'id'   => 'strive_wookc_hide_coupon_code',
		'type' => 'checkbox',
	) );


	/*
		https://www.businessbloomer.com/woocommerce-apply-coupon-programmatically-product-cart/
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable/Disable', 'woocommerce' ),
		'desc' => esc_html__( 'how to add a coupon programmatically if a product is added to cart ?' ),
		'id'   => 'strive_wookc_apply_matched_coupons',
		'type' => 'checkbox',
	) );
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Which product select ?', 'woocommerce' ),
		'desc' => esc_html__( 'how to add a coupon programmatically if a product is added to cart ?' ),
		'id'   => 'strive_wookc_apply_matched_coupons',
		'type' => 'text',
	) );


	/*
		https://www.businessbloomer.com/woocommerce-calculate-sales-coupon-code/
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable/Disable', 'woocommerce' ),
		'desc' => esc_html__( ' Total Sales Generated By Each Coupon Code ?' ),
		'id'   => 'strive_wookc_get_sales_by_coupon',
		'type' => 'checkbox',
	) );


	/*
	
	*/
	$coupon_options->add_field( array(
		'name' => esc_html__( 'Enable/Disable', 'woocommerce' ),
		'desc' => esc_html__( '' ),
		'id'   => '',
		'type' => 'checkbox',
	) );